#! /bin/sh

# -------------------------------------
# AUTOSTART ---------------------------
# -------------------------------------

xrdb -merge ~/.xresources &
xsetroot -cursor_name left_ptr &

xset -dpms &
xset s off &
xset s noblank &
xset -b &

xbacklight -set 10 &
setxkbmap de &

syndaemon -i 0.5 -t -K -R &

feh --bg-scale ~/.wallpaper/1.jpg &
picom -cCzG -t-3 -l-5 -r4 &
nm-applet &
polybar top &
sxhkd &

# -------------------------------------
# BSPWM CONFIG ------------------------
# -------------------------------------

bspc monitor -d						home wwww code music
bspc config border_width			3
bspc config window_gap				0
bspc config normal_border_color		\#3C4146
bspc config active_border_color		\#3C4146
bspc config focused_border_color	\#FF8000

bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config top_padding				30
bspc config bottom_padding			0

bspc config focus_follows_pointer	true
